name:                advent-of-code2021
version:             0.1.0.0
github:              "githubuser/advent-of-code2021"
license:             BSD3
author:              "Christos Dimitroulas"
maintainer:          "c.dimitroulas@gmail.com"
copyright:           "2021 Christos Dimitroulas"

data-files:
  - data/*.*

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-unused-top-binds
  - -Wno-orphans

extra-source-files:
- README.md

dependencies:
- attoparsec >= 0.13
- base >= 4.7 && < 5
- containers
- text

library:
  source-dirs: src

tests:
  advent-of-code-tests:
    source-dirs: test
    build-tools: sydtest-discover
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent-of-code2021
      - sydtest
